kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jupyterlab
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jupyterlab
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jupyterlab
    # replace with namespace where provisioner is deployed
roleRef:
  kind: ClusterRole
  name: jupyterlab
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterlab
  namespace: default
 
